# # # import numpy as np
# import numpy as np
# # # print(np.__version__)

# # # arr=np.array([1,2,3,4])
# # # print(arr)
# # # print(type(arr))
# # # c= np.array([[[1,2],[3,4],[5,6],[7,8]]])
# # # print(c)
# # # print(c.shape)
# # # print(c.size)
# # # print(c.ndim)
# # # print(c.dtype)

# # # a= np.ones((2,3))
# # # print(a)
# # # d=np.arange(0,10,2)
# # # print(d)
# # # d=np.linspace(0,1,5)
# # # print(d)
# # # e=np.eye(3)
# # # print(e)
# # # f=np.random.random((2,3))
# # # print(f)
# # arrr=np.array([[1,2,3],[4,5,6],[7,8,9]])
# # # print(arrr)
# # # print(arrr[0,:])
# # # print(arrr[:,1])

# # # arr=np.array([10,20,30])
# # # print(arr[arr>25])
# # # # print(arr[[0,2,4]])
# # # print(arrr[[0,2],[1,2]])
# # a=np.array([10,20,30,40])
# # b=np.array([1,2,3])
# # # print(a+b)
# # # print(a-b)
# # # print(a*b)
# # # print(a/b)
# # # print(a+arrr)
# # # print(np.sum(arr))
# # # print(np.mean(arr))
# # # print(np.median(arr))
# # # print(np.std(arr))
# # # print(np.var(arr))
# # # print(np.min(arr))
# # # print(np.max(arr))
# # # print(np.argmin(arr))
# # # print(np.argmax(arr))
# # # arr=np.arange(6)
# # # new_arr=arr.reshape(6,1)
# # # print(new_arr)
# # # print(arrr.flatten())
# # # print(arrr.ravel())
# # # print(arrr.transpose())
# # # print(np.concatenate((a,b)))
# # # print(np.split(a,2))
# # z=np.array([[1,2],[3,4]])
# # y=np.array([[5,6],[7,8]])
# # v1=np.array([1,2,3])
# # v2=np.array([4,5,6])
# # result=np.matmul(z,y)
# # print(result)
# # print(np.dot(v1,v2))
# # print(np.linalg.inv(z))
# # print(np.linalg.det(z))
# # # print(np.linalg.eig(z))
# k=np.random.rand(3)
# print(k)
# data=[10,20,30,40,50]
# print(np.random.choice(data,3))
# print(np.random.normal(loc=0,scale=1,size=5))
# np.random.default_rng(seed=5)
# print(np.random.rand(3))